name: ${pom.name}
description: ${pom.description}
version: ${pom.version}
website: ${pom.url}
author: captbunzo

main: net.nyvaria.openfly.OpenFly

commands:
  fly:
    description: Toggle flight on and off
    permission: openfly.fly
    permission-message: You do not have permission to /fly
    usage: /<fly> - Toggle flight on and off

permissions:
  openfly.fly:
    description: Gives access to the fly command
